finances/urls.py
from django.urls import path
from .views import home, fbo_finance

app_name = 'finances'

urlpatterns = [
    path('', home, name='home'),
    path('fbo_finance/', fbo_finance, name='fbo_finance'),
]

fse/urls.py
from django.contrib import admin
from django.urls import path, include
# from avion.views import trigger_error

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("avion.urls", namespace='avion')),
    path('finances/', include("finances.urls", namespace='finances')),
    path('network/', include('network.urls', namespace='network')),
    # path('sentry-debug/', trigger_error),
]

finances/models.py
from django.db import models


# Create your models here.
class Loan(models.Model):
    """
    les données d'emprunts en cours
    """
    types = (
        ('Avion', 'avion'),
        ('FBO', 'fbo'),
        ('Gates', 'gate')
    )

    modes = (
        ('M', 'mensuel'),
        ('J', '30 jours'),
        ('A', 'Autres')
    )

    etats = (
        ('En cours', 'en cours'),
        ('Terminé', 'Terminé')
    )

    type = models.CharField(max_length=10, choices=types)
    mode = models.CharField(max_length=10, choices=modes)
    amount = models.FloatField(default=0.0)
    payback = models.FloatField(default=0.0)
    finance_by = models.CharField(max_length=100, blank=True, null=True)
    date_begin = models.DateField(auto_now_add=False, auto_now=False, blank=True, null=True)
    next_date_payment = models.DateField(auto_now_add=False, auto_now=False, blank=True, null=True)
    title = models.CharField(max_length=100, blank=True, null=True, default='none')
    description = models.TextField(blank=True, null=True)
    status = models.CharField(max_length=10, blank=True, null=True, choices=etats)

    def __str__(self):
        return self.title + ' - ' + self.finance_by


class Project(models.Model):
    """
    les différents projets en cours de développement
    """
    types = (
        ('Avion', 'avion'),
        ('FBO', 'fbo'),
        ('Code', 'code'),
        ('Autres', 'autres')
    )

    title = models.CharField(max_length=100, blank=True, null=True)
    type = models.CharField(max_length=10, choices=types)
    date_begin = models.DateField(auto_created=True, auto_now=False, blank=True, null=True)
    date_end = models.DateField(auto_created=False, auto_now=False, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    amount = models.FloatField(default=0.0)

    def __str__(self):
        return self.title


class FboMonthlySummary(models.Model):
    """
    les résultats mensuels par FBO
    """
    owner = models.CharField(max_length=30)
    icao = models.CharField(max_length=10)
    month = models.IntegerField()
    year = models.IntegerField()
    ass_rental = models.FloatField(default=0.0)
    ass_income = models.FloatField(default=0.0)
    ass_pilot = models.FloatField(default=0.0)
    ass_crew = models.FloatField(default=0.0)
    ass_booking = models.FloatField(default=0.0)

    def __str__(self):
        return self.icao + ' ' + self.owner


class DvaWeek(models.Model):
    """
    les conditions de suivi de DVA
    """
    date_from = models.DateField(blank=True, null=True)
    date_to = models.DateField(blank=True, null=True)
    ident_actif = models.IntegerField(blank=True, null=True)
    week_num = models.IntegerField()
    amount = models.FloatField(default=0.0)

    def __str__(self):
        return str(self.week_num) + ' - ' + str(self.ident_actif)


# class Monthend(models.Model):
#     """
#     la description et le montant des fins de mois
#     """
#     year = models.IntegerField()
#     month = models.IntegerField()
#     aircraft_owner_fee = models.FloatField(default=0.0)
#     aircraft_lease = models.FloatField(default=0.0)
#     gate_rented = models.FloatField(default=0.0)
#     loan_current = models.FloatField(default=0.0)
#     amount = models.FloatField(default=0.0)
#
#     def __str__(self):
#         return str(self.year) + "-" + str(self.month) + " : " + str(self.amount)

finances/views.py
from django.shortcuts import render
from finances.tools import *


# Create your views here.
def home(request):
    actual_loans = ManageLoan().get_loan_list().order_by('-date_begin')
    actif_loans = ManageLoan().get_loan_actif().order_by('-date_begin')
    terminated_loans = ManageLoan().get_loan_terminated().order_by('-date_begin')
    total_loans = ManageLoan().get_total_loan()
    total_paid = ManageLoan().get_actual_pay_back()
    total_due = ManageLoan().get_total_du()
    context = {'loans': actual_loans,
               'loans_actif': actif_loans,
               'loans_terminated': terminated_loans,
               'total_loan': total_loans,
               'total_paid': total_paid,
               'total_due': total_due,
               }
    return render(request, 'finances/home.html', context)


def fbo_finance(request):
    """
    afficher les états financies mensuel des FBO's
    :param request:
    :return:
    """
    return render(request, 'finances/fbo_finance.html', {})

finances/templates/finances/fbo_finance.html
{% extends "base.html" %}
{% load static %}
{% load filters %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <h3>Résultats mensuel par FBO</h3>
                <form action="{% url 'finances:fbo_finance' %}" method="post">{% csrf_token %}
                    <input type="submit" value="Mettre à jour" class="btn btn-primary btn-sm" name="update">
                </form>
            </div>
            <div class="col-sm-6">
                <img src="{% static 'avion/img/fbo.jpg' %}" alt="fbo" width="150" height="150">
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-sm-12">
                <h4>FBO</h4>
            </div>
        </div>
    </div>

{% endblock %}

finances/templates/finances/home.html
{% extends "base.html" %}
{% load static %}
{% load filters %}

{% block content %}

<div class="container">

    <h4>Gestion finances</h4>

    <ul>
        <li>liste des emprunts en cours</li>
        <li>liste des montants nécessaires à la fin du mois courant</li>
        <li>liste des projets d'expansion et leurs coûts prévisionnels</li>
    </ul>

    <div class="row">
        <div class="col-sm-12">
            <table>
                <tr>
                    <th>Les emprunts</th>
                    <th>Total emprunts : {{ total_loan|float_string }}$</th>
                    <th>Total payé : {{ total_paid|float_string }}$</th>
                    <th>Total du : {{ total_due|float_string }}$</th>
                </tr>
            </table>
        </div>
    </div>
    <hr>

   <div class="row">
       <div class="col-sm-12">
           <table>
               <tr>
                   <th>Emprunts en cours</th>
                   <th>Date début</th>
                   <th>Financé par</th>
                   <th>Montant</th>
                   <th>Montant versé</th>
                   <th>Type</th>
               </tr>
               {% for loan in loans_actif %}
                   <tr>
                       <td>{{ loan.title }}</td>
                       <td>{{ loan.date_begin }}</td>
                       <td>{{ loan.finance_by }}</td>
                       <td>{{ loan.amount|float_string }}$</td>
                       <td>{{ loan.payback|float_string }}$</td>
                       <td>{{ loan.type }}</td>
                   </tr>
               {% endfor %}
           </table>
       </div>
   </div>
    <hr>

<div class="row">
       <div class="col-sm-12">
           <table>
               <tr>
                   <th>Emprunts terminés</th>
                   <th>Date début</th>
                   <th>Financé par</th>
                   <th>Montant</th>
                   <th>Montant versé</th>
                   <th>Type</th>
               </tr>
               {% for loan in loans_terminated %}
                   <tr>
                       <td>{{ loan.title }}</td>
                       <td>{{ loan.date_begin }}</td>
                       <td>{{ loan.finance_by }}</td>
                       <td>{{ loan.amount|float_string }}$</td>
                       <td>{{ loan.payback|float_string }}$</td>
                       <td>{{ loan.type }}</td>
                   </tr>
               {% endfor %}
           </table>
       </div>
   </div>
    <hr>
</div>

{% endblock %}