avion/urls.py
from django.urls import path
from .views import accueil, enregistrements, facilities, \
    stats, aircrafts, flights, fbos, formulaire, jobs, aircrafts_retired, \
    fbos_for_sale, vols, aircrafts_cost

app_name = 'avion'

urlpatterns = [
    path('', accueil, name='accueil'),
    # path('update/', update, name='update'),
    # path('importation/', importation, name='importation'),
    # path('affichage/retraite', retraite, name='retraite'),
    path('enregistrements/', enregistrements, name='enregistrements'),
    # path('retraite/', sortir_avion, name='sortir_avion'),
    # path('usage/', usage, name='usage'),
    # path('assignement/', fbo_assignements, name='assignements'),
    # path('fbo/', fbo, name='fbo'),
    path('facilities/', facilities, name='facilities'),
    path('stats/', stats, name='stats'),
    path('aircrafts/', aircrafts, name='aircrafts'),
    path('aircrafts_cost/', aircrafts_cost, name='aircrafts_cost'),
    path('flights/', flights, name='flights'),
    path('fbos/', fbos, name='fbos'),
    path('fbosSale/', fbos_for_sale, name='fbos_for_sale'),
    path('jobs/', jobs, name='jobs'),
    path('formulaire/', formulaire, name='formulaire'),
    path('retired/', aircrafts_retired, name='retired'),
    path('vols/', vols, name='vols'),
]

fse/urls.py
from django.contrib import admin
from django.urls import path, include
# from avion.views import trigger_error

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("avion.urls", namespace='avion')),
    path('finances/', include("finances.urls", namespace='finances')),
    path('network/', include('network.urls', namespace='network')),
    # path('sentry-debug/', trigger_error),
]

avion/forms.py
from django import forms
from .models import Aircraft


class SelectionAvionForm(forms.Form):
    Selection = forms.CharField(widget=forms.Select)


class AircraftInfoForm(forms.ModelForm):
    class Meta:
        model = Aircraft
        fields = ['makemodel', 'registration', 'airframe_time', 'monthlyfee']

avion/views.py
from django.shortcuts import render
from django.db.models.query import QuerySet
# from .tools import mesurer_temps
from .update_fse import *
from .models import Bank, AircraftRetired, Use, Assignment, Fbo
from django.db.models import Sum
from .forms import SelectionAvionForm


# from django.db.models.functions import Trunc


# Create your views here.

# test sentry debugger
#
# def trigger_error(request):
#     division_by_zero = 1 / 0


def accueil(request):
    if request.POST.get('maj'):
        UpdateFSE().update_gaugauair()

    aircrafts = ManageAircrafts().get_aircrafts_list()
    fbos = ManageFbos().get_list()
    context = {'aircrafts': aircrafts,
               'fbos': fbos,
               }
    return render(request, "avion/accueil.html", context)


# @mesurer_temps(1)
def stats(request):
    """
    update stats datas
    :param request:
    :return:
    """
    if request.POST.get('update'):
        ManageStats().update()

    if request.POST.get('update_dva'):
        ManageJobs().update_dva_week()

    statistics = ManageStats().get_list()
    investissements_fbo = ManageFacilities().get_investissement_total()
    profit_avion = ManageAircrafts().get_profit_total()
    cash_available = ManageStats().get_cash_amount()
    # incomes_a2b = ManageJobs().get_a2b_jobs()
    incomes_dva = ManageJobs().get_dva_jobs()
    incomes_dva_week_current = ManageJobs().get_dva_jobs_week_current()
    incomes_oac = ManageJobs().get_oac_jobs()
    flights_challenge = ManageFlights().get_challenge_info()
    recap_challenge = ManageFlights().get_challenge_recap()
    last_date = ManageBank().get_last_date()
    context = {'statistics': statistics,
               'profits_avion': profit_avion,
               'investissement_fbo': investissements_fbo,
               'cash_available': cash_available,
               # 'a2b_jobs': incomes_a2b,
               'dva_jobs': incomes_dva,
               'dva_jobs_week_current': incomes_dva_week_current,
               'oac_jobs': incomes_oac,
               'flights_challenge': flights_challenge,
               'recap_challenge': recap_challenge,
               'last_date': last_date,
               }
    return render(request, 'avion/stats.html', context)


def aircrafts(request):
    """
    update aircrafts general datas
    :param request:
    :return:
    """
    if request.POST.get('update_list'):
        ManageAircrafts().update_list()
        ManageFlights().update()

    if request.POST.get('update_use'):
        ManageAircrafts().update_aircrafts_use_datas()

    aircrafts_list = ManageAircrafts().get_aircrafts_actif_list()
    # aircrafts_cost = ManageAircrafts().get_use_datas()
    monthlyfee_cost = ManageAircrafts().get_total_monthly_fee()
    # profit_total = ManageAircrafts().get_profit_total()
    last_date = ManageBank().get_last_date()
    context = {'aircrafts_list': aircrafts_list,
               # 'aircrafts_cost': aircrafts_cost,
               'monthlyfee_cost': monthlyfee_cost,
               # 'profit_total': profit_total,
               'last_date': last_date}
    return render(request, 'avion/aircrafts.html', context)


def aircrafts_cost(request):
    """
    obtenir les coûts et bénéfices par avion
    :param request:
    :return:
    """
    if request.POST.get('update_use'):
        ManageAircrafts().update_aircrafts_use_datas()

    ac_cost = ManageAircrafts().get_use_datas()
    profit_total = ManageAircrafts().get_profit_total()
    last_date = ManageBank().get_last_date()
    context = {'aircrafts_cost': ac_cost,
               'profit_total': profit_total,
               "last_date": last_date}

    return render(request, 'avion/aircrafts_cost.html', context)


def aircrafts_retired(request):
    """
    show retired environment
    :param request:
    :return:
    """
    acs = ManageAircrafts().get_aircrafts_list()
    context = {'aircrafts': acs}
    return render(request, 'avion/aircrafts_retired.html', context)


def fbos(request):
    """
    update FBO's datas™
    :param request:
    :return:
    """
    if request.POST.get('update_list'):
        ManageFbos().update_list()

    fbos_infos = ManageGroup().get_infos_fbo_per_network('GaugauAir Chambers')
    fbos_list = ManageFbos().get_list()
    last_date = ManageBank().get_last_date()
    context = {'fbos_list': fbos_list,
               'last_date': last_date,
               'chambers': fbos_infos}
    return render(request, 'avion/fbos.html', context)


def fbos_for_sale(request):
    """
    show fbo's for sale for a specific location
    :param request:
    :param location:
    :return:
    """
    if request.method == "POST":
        location = request.POST.get('localisation')
        fbos_list = ManageFbos().get_fbo_for_sale_localisation(location)
        context = {'fbos_list': fbos_list,
                   'location': location,
                   }
    else:
        context = {}
    return render(request, 'avion/fbovente.html', context)


def facilities(request):
    """
    Update Facilities datas
    :param request:
    :return:
    """
    if request.POST.get('update'):
        ManageFacilities().update_list()

    fac = ManageFacilities().get_list().order_by('-profits')
    rent_cost = ManageFacilities().get_total_monthly_rent_cost()
    incomes_total = ManageFacilities().get_incomes_total()
    profits_total = abs(ManageFacilities().get_profit_total())
    return_rate = ManageFacilities().get_incomes_total() / abs(ManageFacilities().get_profit_total()) * 100
    last_date = ManageBank().get_last_date()

    context = {'facilities': fac,
               'profits': profits_total,
               'incomes': incomes_total,
               'return_rate': return_rate,
               'rent_costs': rent_cost,
               'last_date': last_date}
    return render(request, 'avion/facilities.html', context)


def enregistrements(request):
    if request.POST.get('update'):
        ManageBank().update()

    datas = Bank.objects.all().order_by("-date_item")[:300]
    last_date = ManageBank().get_last_date()
    context = {'datas': datas,
               'last_date': last_date
               }
    return render(request, 'avion/enregistrements.html', context)


def jobs(request):
    accounts = Accounts().get_list_accounts()
    context = {'accounts': accounts}
    return render(request, 'avion/jobs.html', context)


def formulaire(request):
    fbos = ManageFbos().get_list_icao()
    context = {'fbos': fbos}
    return render(request, 'avion/formulaire.html', context)


def flights(request):
    context = {}

    if request.method == "POST":

        last_date = ManageBank().get_last_date()
        actual_registration = request.POST.get('aircraft')
        print(f"Immat actual : {actual_registration}")
        if request.POST.get('modify_registration'):
            actual_registration = request.POST.get('registration_source')
            new_registration = request.POST.get('registration')
            print(f"Immat source : {actual_registration}")
            print(f"Immat future : {new_registration}")
            ManageAircrafts().change_registration(actual_registration, new_registration)
            registration = new_registration
        else:
            registration = actual_registration

        print(f"Immat utile : {registration}")
        aircraft_obj = ManageAircrafts().get_by_registration(registration)
        aircraft_flights = ManageFlights().get_last_50_by_registration(registration)
        leaser = ManageFlights().get_lease_from(registration)
        income_total = ManageFlights().get_total_income_by_registration(registration)
        flight_time_total = ManageFlights().get_total_flight_time_by_registration(registration)
        ratio_by_nm = ManageFlights().get_ratio_by_nm(registration)
        ratio_by_hour = ManageFlights().get_ratio_by_hour(registration)
        ratio_finance = ManageFlights().get_ratio_financial(registration)
        context = {'aircraft': aircraft_obj,
                   'flights': aircraft_flights,
                   'last_date': last_date,
                   'income_total': income_total,
                   'flight_time_total': flight_time_total,
                   'ratio_by_hour': ratio_by_hour,
                   'ratio_by_nm': ratio_by_nm,
                   'ratio_finance': ratio_finance,
                   'leaser': leaser,
                   }

    return render(request, 'avion/flights.html', context)


def vols(request):
    context = {}
    avion = ''
    fbo = ''

    # bouton 'Mettre à jour' (dansla base de données locale)
    if request.POST.get('update'):
        ManageFlights().update()

    # bouton "Vols" pour trouver les dix derniers vols d'un avion
    if request.POST.get('lookup'):
        avion = request.POST.get('registration', 'Problème avec le formulaire de saisie')

        vols = ManageFlights().get_by_registration(avion)[:10]

        context = {'avion': avion,
                   'flights': vols,
                   }

    # bouton 'Confirmer" pour trouver les données d'une sous-ensemble de vols
    if request.POST.get('confirm'):
        start = request.POST.get('start')
        stop = request.POST.get('stop')

        result = ManageFlights().get_by_ids(start, stop)
        vols = ManageFlights().get_by_registration(avion)[:10]

        context = {'test': 'lookup : OK',
                   'results': result,
                   'flights': vols}

    return render(request, 'avion/vols.html', context)

avion/templates/avion/aircrafts.html
{% extends "base.html" %}
{% load static %}
{% load filters %}

{% block content %}


    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h4>Description de la flotte active</h4>
                <p>Dernière mise à jour le : {{ last_date }}</p>
                <p>Total de frais fixes par mois: {{ monthlyfee_cost|float_string}}$</p>

                <form action="{% url 'avion:aircrafts' %}" method="post">{% csrf_token %}
                    <input type="submit" value="Mettre à jour" class="btn btn-primary btn-sm" name="update_list">
                </form>

                <table>
                    <tr>
                        <th>Immat</th>
                        <th>Type</th>
                        <th>Aéroport</th>
                        <th>Base</th>
                        <th>Structure</th>
                        <th>Moteur</th>
                        <th>100hr</th>
                        <th>Frais mensuels</th>
                        <th>Locateur/Propriétaire</th>
                    </tr>
                    {% for aircraft in aircrafts_list %}
                        <tr>
                            <td>
                                <form action="{% url 'avion:flights' %}" method="post">{% csrf_token %}
                                    <input type="submit" value={{ aircraft.registration }} name='aircraft'>
                                </form>
                            </td>
                            <td>{{ aircraft.makemodel }}</td>
                            <td>{{ aircraft.location }}</td>
                            <td>{{ aircraft.home }}</td>
                            <td>{{ aircraft.airframe_time }}h</td>
                            <td>{{ aircraft.engine_time }}h</td>
                            <td>{{ aircraft.last100 }}h</td>
                            <td>{{ aircraft.monthlyfee|float_string }}$</td>
                            <td>{{ aircraft.leasedfrom }}</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
        <hr>
    </div>
    <hr>

{% endblock %}

avion/templates/avion/aircrafts_cost.html
{% extends "base.html" %}
{% load static %}
{% load filters %}

{% block content %}


    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h4 >Répartition du travail par avion</h4>
                <p><strong>Profit généré par les avions : {{ profit_total|float_string }}$</strong></p>
                <form action="{% url 'avion:aircrafts' %}" method="post">{% csrf_token %}
                    <input type="submit" value="Mettre à jour" class="btn btn-primary btn-sm" name="update_use">
                </form>
                <table>
                    <tr>
                        <th>Immat</th>
                        <th>Location</th>
                        <th>Travail</th>
                        <th>Entretien</th>
                        <th>Carburant</th>
                        <th>lease/Achat</th>
                        <th>Profits</th>
                        <th>Ratio NM</th>
                    </tr>

                    {% for aircraft in aircrafts_cost %}
                        <tr>
                            <td>{{ aircraft.immat }}</td>
                            <td>{{ aircraft.gain_location|float_string }}$</td>
                            <td>{{ aircraft.gain_travail|float_string }}$</td>
                            <td>{{ aircraft.frais_entretien|float_string }}$</td>
                            <td>{{ aircraft.frais_carburant|float_string }}$</td>
                            <td>{{ aircraft.lease|float_string }}$</td>
                            <td>{{ aircraft.profits|float_string }}$</td>
                            <td>{{ aircraft.ratio_nm|float_string }}$</td>
                        </tr>

                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
    <hr>

{% endblock %}

avion/templates/avion/aircrafts_retired.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">

   <div class="row">
            <div class="col-sm-6">
                <h4>Choisir un avion</h4>
{#                <form action="{% url 'avion:retired' %}" method="post">{% csrf_token %}#}
                    <table>
                        <tr>
                            <th>Immatriculation</th>
                        </tr>
                        {% for aircraft in aircrafts %}
                            <tr>
                                <td>
                                    <label for={{ aircraft.registration }}>{{ aircraft.registration }}</label>
                                    <input name={{ aircraft.registration }} type="checkbox" value={{ aircraft.registration }}
                                            id={{ aircraft.registration }}>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>

{#                    <input class="btn btn-primary btn-sm" type="submit" value="Choisir">#}
{#                </form>#}
            </div>
            <div class="col-sm-6">
                <h4>Informations</h4>
                <form action="" method="post">{% csrf_token %}
                    <p>Cliquez sur le bouton ci-dessous pour afficher les informations de l'avion concerné</p>
                    <input type="submit" id="confirm" class="btn btn-primary btn-sm" value="Confirmer">
                </form>
            </div>
   </div>

        <hr>
</div>

{% endblock %}

avion/templates/avion/facilities.html
{% extends "base.html" %}
{% load filters %}

{% block content %}


    <div class="container">
        <div class="row">
            <div class="col_sm_12">
               <h4>Information Facilities</h4>
                <p>Dernière mise à jour le : {{ last_date }}</p>
                <p><strong>Revenus générés par les FBO's : {{ incomes|float_string }}$</strong></p>
                <p><strong>Investissements dans les FBO's : {{ profits|float_string}}$</strong></p>
                <p><strong>Retour sur investissement : {{ return_rate|float_string}}%</strong></p>
                <form action="{% url 'avion:facilities' %}" method="post">{% csrf_token %}
                    <input type="submit" value="Mettre à jour" class="btn btn-primary btn-sm" name="update">
                </form>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <table>
                    <tr>
                        <th>ICAO</th>
                        <th>Lieu</th>
                        <th>Portes</th>
                        <th>Destinations</th>
                        <th>Mensuel</th>
                        <th>Achat</th>
                        <th>Revenus</th>
                        <th>Profits</th>
                    </tr>
                    {% for facility in facilities %}
                    <tr>
                        <td><a href="http://server.fseconomy.net/airport.jsp?icao={{ facility.icao }}" target="_blank">{{ facility.icao }}</a></td>
                        <td>{{ facility.location }}</td>
                        <td>{{ facility.gatestotal }}</td>
                        <td>{{ facility.destinations }}</td>
                        <td>{{ facility.monthly_cost }}$</td>

{#                            {% if facility.rentcost == 0.0 %}#}
                        <td>{{ facility.buildcost|float_string:'0' }}$</td>
{#                            {% else %}#}
{#                                <td>{{ facility.rentcost }} + {{ facility.buildcost }}$</td>#}
{#                            {% endif %}#}
                        <td>{{ facility.incomes|float_string }}$</td>
                        <td>{{ facility.profits|float_string }}$</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>

    </div>

{% endblock %}

avion/templates/avion/fbos.html
{% extends "base.html" %}

{% block content %}


    <div class="container">
        <div class="row">
            <div class="col_sm_12">
               <h4>Information FBO's</h4>
                <p>Dernière mise à jour le : {{ last_date }}</p>
                <form action="{% url 'avion:fbos' %}" method="post">{% csrf_token %}
                    <input type="submit" value="Mettre à jour" class="btn btn-primary btn-sm" name="update_list">
                </form>
                <form action="{% url 'avion:fbos_for_sale' %}" method="post">{% csrf_token %}
                    <input type="text" placeholder="localisation" name="localisation">
                    <input type="submit" value="À vendre" class="btn btn-primary btn-sm" name="location">
                </form>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <table class="table">
                    <thead>
                        <tr>
                            <th>ICAO</th>
                            <th>Lieu</th>
                            <th>Propriétaire</th>
                            <th>Portes</th>
                            <th>Louées</th>
                            <th>100LL</th>
                            <th>JetA</th>
                            <th>Fourniture</th>
                            <th>Nb jours</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for fbo in fbos_list %}
                        <tr>
                                <td><a href="http://server.fseconomy.net/airport.jsp?icao={{ fbo.icao }}" target="_blank">{{ fbo.icao }}</a></td>
                                <td>{{ fbo.airport }}</td>
                                <td>{{ fbo.owner }}</td>
                                <td>{{ fbo.gates }}</td>
                                <td>{{ fbo.gatesrented }}</td>
                                <td>{{ fbo.fuel100ll }} Kg</td>
                                <td>{{ fbo.fueljeta }} Kg</td>
                                <td>{{ fbo.supplies }} Kg</td>
                                <td>{{ fbo.suppliedday }} jours</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

    </div>

{% endblock %}

avion/templates/avion/fbovente.html
{% extends "base.html" %}
{% load filters %}

{% block content %}


    <div class="container">
        <h4 >FBO's à vendre</h4>
        <div class="row">
            <div class="col-sm-12">
                    <h3>Les FBO's à vendre - {{ location }}</h3>
                    <table>
                        <tr>
                            <th>Aéroport</th>
                            <th>ICAO</th>
                            <th>Lieu</th>
                            <th>Lots</th>
                            <th>Portes</th>
                            <th>Portes louées</th>
{#                            <th>Lots</th>#}
                            <th>Status</th>
                            <th>Atelier</th>
                            <th>Prix</th>
                        </tr>
                        {% for fbo in fbos_list %}
                        <tr>
                            <td>{{ fbo.airport}}</td>
                            <td>{{ fbo.icao }}</td>
                            <td>{{ fbo.location }}</td>
                            <td>{{ fbo.lots }}</td>
                            <td>{{ fbo.gates}}</td>
                            <td>{{ fbo.gatesrented }}</td>
{#                            <td>{{ fbo.lots }}</td>#}
                            <td>{{ fbo.status }}</td>
                            <td>{{ fbo.repairshop }}</td>
                            <td>{{ fbo.sellprice|float_string }}$</td>
                            <td>chk</td>

                        </tr>
                    {% endfor %}
                    </table>
            </div>
            <div class="col-sm-3">
{#                <form action="{% url 'avion:fbos_for_sale' %}">#}
{#                    <p><input type="text" id="localisation"></p>#}
{#                    <p><input type="submit" value="Confirmez"></p>#}
{#                </form>#}
            </div>
        </div>
    </div>

{% endblock %}

avion/templates/avion/flights.html
{% extends "base.html" %}
{% load filters %}

{% block content %}


    <div class="container">
        <div class="row">
            <div class="col_sm_12">
                <h4>Information de vol pour {{ aircraft.registration }}</h4>
                <p>Dernière mise à jour le : {{ last_date }}</p>
                {#                <form action="{% url 'avion:flights' %}" method="post">{% csrf_token %}#}
                {#                    <input type="submit" value="Mettre à jour" class="btn btn-primary btn-sm" name="update">#}
                {#                </form>#}
            </div>
        </div>

        <div class="row">
            <div class="col-sm-4">
                {% if flights %}
                    <h5>Informations générales</h5>
                    <table>
                        <tr>
                            <td>Identifiant</td>
                            <td>{{ aircraft.serialnumber }}</td>
                        </tr>
                        <tr>
                            <td>Modèle</td>
                            <td>{{ aircraft.makemodel }}</td>
                        </tr>
                        <tr>
                            <td>Propriétaire</td>
                            <td>{{ aircraft.owner }}</td>
                        </tr>
                        <tr>
                            <td>Locateur</td>
                            <td>{{ leaser }}</td>
                        </tr>
                        <tr>
                            <td>Base d'opération</td>
                            <td>{{ aircraft.home }}</td>
                        </tr>
                        <tr>
                            <td>Localisation actuelle</td>
                            <td>{{ aircraft.location }}</td>
                        </tr>
                        <tr>
                            <td>Temps de vol total</td>
                            <td>{{ flight_time_total|float_string:'0' }}h</td>
                        </tr>
                        <tr>
                            <td>Revenus total</td>
                            <td>{{ income_total|float_string:'0' }}$</td>
                        </tr>
                        <tr>
                            <td>Revenus par NM</td>
                            <td>{{ ratio_by_nm|float_string:'0' }}$</td>
                        </tr>
                        <tr>
                            <td>Revenus par heure</td>
                            <td>{{ ratio_by_hour|float_string:'0' }}$</td>
                        </tr>
                        <tr>
                            <td>Retour sur investissement</td>
                            <td>{{ ratio_finance|float_string:'0' }}%</td>
                        </tr>

                    </table>
                {% endif %}
                <hr>
                <div class="accordion" id="accordionretired">
                    <div class="card">
                        <div class="card-header" id="headingretired">
                            <h2 class="mb-0">
                                <button class="btn btn-primary btn-sm" type="button" data-toggle="collapse"
                                        data-target="#collapseretired" aria-expanded="true"
                                        aria-controls="collapseretired">
                                    <h5>Retirer</h5>
                                </button>
                            </h2>
                        </div>

                        <div id="collapseretired" class="collapse collapse" aria-labelledby="headingretired"
                             data-parent="#accordionretired">
                            <div class="card-body">
                                <p>Voulez-vous retirer l'avion immatriculé
                                    <br><strong>{{ aircraft.registration }}</strong>?</p>
                                <form action="#" method="post">{% csrf_token %}
                                    <input type="submit" value="Confirmer" class="btn btn-primary btn-sm"
                                           name="confirmed_retired">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <hr>
                <div class="accordion" id="accordionregistration">
                    <div class="card">
                        <div class="card-header" id="headingregistration">
                            <h2 class="mb-0">
                                <button class="btn btn-primary btn-sm" type="button" data-toggle="collapse"
                                        data-target="#collapseregistration" aria-expanded="true"
                                        aria-controls="collapseregistration">
                                    <h5>Modifier immatriculation</h5>
                                </button>
                            </h2>
                        </div>

                        <div id="collapseregistration" class="collapse collapse" aria-labelledby="headingregistration"
                             data-parent="#accordionregistration">
                            <div class="card-body">
                                <p>L'immatriculation actuelle est : <br>
                                    <strong>{{ aircraft.registration }}</strong>?</p>
                                <form action="#" method="post">{% csrf_token %}
                                    <input type="text" name="registration_source" value={{ aircraft.registration }}>
                                    <input type="text" placeholder="Nouvelle immatriculation" name="registration">
                                    <input type="submit" value="Confirmer" class="btn btn-primary btn-sm"
                                           name="modify_registration">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                {% if flights %}
                    <h5>Les vols du mois </h5>
                    <table>
                        <tr>
                            <th>Date</th>
                            <th>Origine</th>
                            <th>Destination</th>
                            <th>Durée du vol</th>
                            <th>Distance</th>
                            <th>Revenus</th>
                        </tr>
                        {% for flight in flights %}
                            <tr>
                                <td>{{ flight.time }}</td>
                                <td>{{ flight.origine }}</td>
                                <td>{{ flight.destination }}</td>
                                <td>{{ flight.flighttime }}</td>
                                <td>{{ flight.distance }}</td>
                                <td>{{ flight.income|float_string }}$</td>
                            </tr>
                        {% endfor %}
                    </table>
                {% else %}
                    <p>Aucune donnée de vol {{ aircraft }}</p>
                {% endif %}
            </div>
        </div>

    </div>

{% endblock %}