avion/urls.py
from django.urls import path
from .views import accueil, enregistrements, facilities, \
    stats, aircrafts, flights, fbos, formulaire, jobs, aircrafts_retired, \
    fbos_for_sale, vols, aircrafts_cost

app_name = 'avion'

urlpatterns = [
    path('', accueil, name='accueil'),
    # path('update/', update, name='update'),
    # path('importation/', importation, name='importation'),
    # path('affichage/retraite', retraite, name='retraite'),
    path('enregistrements/', enregistrements, name='enregistrements'),
    # path('retraite/', sortir_avion, name='sortir_avion'),
    # path('usage/', usage, name='usage'),
    # path('assignement/', fbo_assignements, name='assignements'),
    # path('fbo/', fbo, name='fbo'),
    path('facilities/', facilities, name='facilities'),
    path('stats/', stats, name='stats'),
    path('aircrafts/', aircrafts, name='aircrafts'),
    path('aircrafts_cost/', aircrafts_cost, name='aircrafts_cost'),
    path('flights/', flights, name='flights'),
    path('fbos/', fbos, name='fbos'),
    path('fbosSale/', fbos_for_sale, name='fbos_for_sale'),
    path('jobs/', jobs, name='jobs'),
    path('formulaire/', formulaire, name='formulaire'),
    path('retired/', aircrafts_retired, name='retired'),
    path('vols/', vols, name='vols'),
]

fse/urls.py
from django.contrib import admin
from django.urls import path, include
# from avion.views import trigger_error

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("avion.urls", namespace='avion')),
    path('finances/', include("finances.urls", namespace='finances')),
    path('network/', include('network.urls', namespace='network')),
    # path('sentry-debug/', trigger_error),
]

network/urls.py
from django.urls import path
from .views import nml, groups, description, assignement, pax, fresno

app_name = 'network'

urlpatterns = [
    path('', nml, name='home'),
    path('group/', groups, name='groups'),
    path('repartition/', description, name='repartition'),
    path('assignement/', assignement, name='assignement'),
    path('pax/', pax, name='pax'),
    path('description/', description, name='description'),
    path('fresno/', fresno, name='fresno'),
]

templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'avion/css/fse.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'avion/img/logo_icone_01.png' %}">
      <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
    <title>Gestion avion</title>
</head>
<body>

    <div class="container">
        {% block navbar %}
            {% include 'navbar.html' %}
        {% endblock %}
        <hr>

        {% block titre %}
            <div class="jumbotron">
                <div class="row">
                    <p class="col-sm-6">
                        <img src="{% static 'avion/img/logo04.png' %}" alt="logo" width="300" height="100">
                        <br>
                        Voler encore!
                    </p>

                    <div class="col-sm-3">

                        <h3>Gestion de la compagnie</h3>
                        <p>
                            Une flotte opérationnelle <br>
                            Des FBO's efficaces <br>
                            quelques heures de plaisir!
                        </p>
                        <form action="{% url 'avion:accueil' %}" method="post">{% csrf_token %}
                            <input type="submit" value="Mettre à jour" class="btn btn-success btn-sm" name="maj">
                        </form>
{#                        <p><small>ATTENTION danger!</small></p>#}

                    </div>
                    <div class="col-sm-3">
                        <p><img src="{% static 'avion/img/C208.png' %}" alt="Avion compagnie" width="250" height="120"></p>
                    </div>
                </div>

            </div>

            <hr>
        {% endblock %}


        {% block content %}

        {% endblock %}

        {% block footer %}
            {% include "footer.html" %}
        {% endblock %}

    </div>

</body>
</html>

templates/footer.html
    <footer class="footer-main">
        <div class="container">
{#            <div class="row">#}
{#                <div class="col-lg-3">#}
{#                    <h3>app_name</h3>#}
{#                    <ul>#}
{#                        <li><a href="#">data_test</a></li>#}
{#                        <li><a href="#">data_test</a></li>#}
{#                        <li><a href="#">data_test</a></li>#}
{#                        <li><a href="#">data_test</a></li>#}
{#                        <li><a href="#">data_test</a></li>#}
{#                        <li><a href="#">data_test</a></li>#}
{#                        <li><a href="#">data_test</a></li>#}
{#                    </ul>#}
{#                </div>#}
{##}
{#                <div class="col-lg-3">#}
{#                    <h3>Ressources</h3>#}
{#                    <ul>#}
{#                        <li><a href="#">Communauté des développeurs</a></li>#}
{#                        <li><a href="#">Support</a></li>#}
{#                        <li><a href="#">Registraire</a></li>#}
{#                        <li><a href="#">Blogs</a></li>#}
{#                        <li><a href="#">Webinaires</a></li>#}
{#                    </ul>#}
{#                </div>#}
{#                <div class="col-lg-2">#}
{#                    <h3>Univ</h3>#}
{#                    <ul>#}
{#                        <li><a href="#">Contactez-nous</a></li>#}
{#                        <li><a href="#">Partenaires</a></li>#}
{#                        <li><a href="#">Témoignages</a></li>#}
{#                        <li><a href="#">Emplois</a></li>#}
{#                    </ul>#}
{#                </div>#}
{#                <div class="col-lg-2">#}
{#                    <h3 class="contacts">Contacts</h3>#}
{#                    <ul>#}
{#                        <li><a href="#">data_test</a></li>#}
{#                        <li><a href="#">data_test</a></li>#}
{#                        <li><a href="mailto:admin@tradom.ca">Web maistre</a></li>#}
{#                    </ul>#}
{#                </div>#}
{#                <div class="col-lg-2">#}
{#                    <h3>Social</h3>#}
{#                    <ul>#}
{#                        <li class="facebook" title="Facebook"><a href="#">Facebook</a></li>#}
{#                        <li class="gPlus" title="Google+"><a href="#">Google+</a></li>#}
{#                        <li class="in" title="LinkedIn"><a href="#">LinkedIn</a></li>#}
{#                        <li class="twitter" title="Twitter"><a href="#">Twitter</a></li>#}
{#                        <li class="youtube" title="YouTube"><a href="#">YouTube</a></li>#}
{#                    </ul>#}
{#                </div>#}
{#            </div>#}
            <br class="clr"/>
            <div class="footer-main-bas">
                <div class="row">
                    <p>
                        &copy; 2018-2019 GAUGAUAIR. Tous droits réservés.
                        Développé par FORMAPRO avec <a href="https://www.jetbrains.com/pycharm/">PyCharm </a>et
                        <a href="https://www.djangoproject.com/"> Django</a>
{#                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#}
{#                        <a href="#">Vie privée</a> | <a href="#">Limites d'utilisation</a>#}
                    </p>
                    <br class="clr"/>
                </div>
            </div>
        </div>
    </footer>

templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #51d1eb">
    <a class="navbar-brand" href="{% url 'avion:accueil' %}">
        <img src="{% static 'avion/img/logo_icone_01.png' %}" width="45" height="30"
             class="d-inline-block align-top" alt="logo">
    </a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'avion:stats' %}">Statistiques
                    <span class="sr-only">(current)</span></a>
            </li>
{#            <li class="nav-item active">#}
{#                <a class="nav-link" href="{% url 'network:fresno' %}">Fresno#}
{#                    <span class="sr-only">(current)</span></a>#}
{#            </li>#}
{#            <li class="nav-item dropdown active">#}
{#                <a class="nav-link dropdown-toggle" href="#" id="networkDropdown"#}
{#                   role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
{#                    Réseaux#}
{#                </a>#}
{#                <div class="dropdown-menu" aria-labelledby="networkDropdown">#}
{#                    <a class="dropdown-item" href="{% url 'network:home' %}">Network Manager Labs</a>#}
{#                    <a class="dropdown-item" href="{% url 'network:description' %}">Description</a>#}
{#                    <div class="dropdown-divider"></div>#}
{#                    <a class="dropdown-item" href="{% url 'avion:fbos' %}">FBO's</a>#}
{#                    <a class="dropdown-item" href="{% url 'avion:facilities' %}">Facilities</a>#}
{#                    <a class="dropdown-item disabled" href="{% url 'network:pax' %}">Pax</a>#}
{#                </div>#}
{#            </li>#}
{#            <li class="nav-item dropdown active">#}
{#                <a class="nav-link dropdown-toggle" href="#" id="aircraftdropdown"#}
{#                   role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
{#                    Avions#}
{#                </a>#}
{#                <div class="dropdown-menu" aria-labelledby="aircraftdropdown">#}
{#                    <a class="dropdown-item" href="{% url 'avion:aircrafts' %}">Flotte</a>#}
{#                    <a class="dropdown-item" href="{% url 'avion:aircrafts_cost' %}">Répartition des gains</a>#}
{#                </div>#}
{#            </li>#}
            <li class="nav-item dropdown active">
                <a class="nav-link dropdown-toggle" href="#" id="financedropdown"
                   role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Finances
                </a>
                <div class="dropdown-menu" aria-labelledby="financedropdown">
                    <a class="dropdown-item" href="{% url 'finances:home' %}">Emprunts</a>
                    <a class="dropdown-item" href="{% url 'avion:enregistrements' %}">Récapitulatif</a>
                </div>
            </li>

        </ul>
    </div>
    <div id="navbar" class="navbar-right">
        <a class="nav-item active" href="{% url 'admin:index' %}">Administration</a>
    </div>
</nav>